// components/content.vue
<template>
  <div>
    <h1 class="text-3xl font-bold text-center pt-12">
      Konten Mendidik
    </h1>
    <div class="flex flex-wrap py-10 justify-center">

      <div class="cards max-w-md mb-auto mt-5 rounded overflow-hidden shadow-lg mx-5">
        <a href="https://medium.com/@gelembungsahabat/deteksi-warna-dengan-metode-image-thresholding-opencv-python-3-f3686de4308">

          <img
            src="../assets/images/imagethres.png"
            alt="image thresholding"
            class="w-full"
          >
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">
              Image Thresholding with OpenCV Python3
            </div>
            <p class="text-gray-700 text-base break-word">Pengenalan dasar image thresholding beserta source codenya</p>
          </div>
          <div class="px-6 pt-4 pb-2 ">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Programming</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Python</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#OpenCV</span>
          </div>
        </a>
      </div>

      <div class="cards max-w-md mb-auto mt-5 rounded overflow-hidden shadow-lg mx-5">
        <a href="https://medium.com/@gelembungsahabat/pengenalan-reactjs-40ffa31ae9c7">

          <img
            src="../assets/images/reactjs.png"
            alt="pengenalan reactjs"
            class="w-full"
          >
          <div class="px-6 py-4 mb-0">
            <div class="font-bold text-xl mb-2">
              Pengenalan ReactJS
            </div>
            <p class="text-gray-700 text-base break-word">Pengenalan salah satu framework JS paling populer yaitu ReactJS </p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Programming</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Javascript</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#ReactJS</span>
          </div>
        </a>
      </div>
      <div class="cards max-w-md mb-auto mt-5 rounded overflow-hidden shadow-lg mx-5">
        <a href="https://medium.com/@gelembungsahabat/persiapan-membuat-website-dengan-reactjs-435ccac65c54">
          <img
            src="../assets/images/persiapanreact.png"
            alt="persiapan bikin project reactjs"
            class="w-full"
          >
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">
              Persiapan Membuat Web dengan ReactJS
            </div>
            <p class="text-gray-700 text-base break-word">Materi tentang setup project ReactJS beserta penjelasannya</p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Programming</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Javascript</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#ReactJS</span>
          </div>
        </a>
      </div>
      <div class="cards max-w-md mb-auto mt-5 rounded overflow-hidden shadow-lg mx-5">
        <a href="https://medium.com/@gelembungsahabat/belajar-membuat-static-site-menggunakan-reactjs-part1-4bb9a3a02307">
          <img
            src="../assets/images/staticwebreact1.png"
            alt="bikin static web pake reactjs part 1"
            class="w-full"
          >
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">
              Belajar Membuat Static Site Menggunakan ReactJS #part1
            </div>
            <p class="text-gray-700 text-base break-word">Belajar membuat skeleton atau kerangka dari project web dan belajar mengenai `Components`</p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Programming</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#Javascript</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-2 text-sm font-semibold text-gray-700 mr-2 mb-2">#ReactJS</span>
          </div>
        </a>
      </div>
      <div class="cards max-w-md mb-auto mt-5 rounded overflow-hidden shadow-lg mx-5">
        <a href="https://medium.com/@gelembungsahabat/dasar-vcs-version-control-system-789b6793bcb9">

          <img
            src="../assets/images/git.png"
            alt="basic Git"
            class="w-full"
          >
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">
              Dasar VCS (Version Control System)
            </div>
            <p class="text-gray-700 text-base break-word">ini pengetahuan dasar tentang cara pengoperasian VCS.
              VCS Bukan singkatan dari Video Call S*x ya, tapi Version Control System. Dalam hal ini mengarah ke Git </p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#Programming</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#Git</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#Basic</span>
          </div>
        </a>
      </div>
      <div class="cards max-w-md mb-auto mt-5 rounded overflow-hidden shadow-lg mx-5">
        <nuxt-link to="/about">
          <img
            src="../assets/images/mirai.jpg"
            alt="mirai"
            class="w-full"
          >
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">
              coba
            </div>
            <p class="text-gray-700 text-base break-word">aku bingug kate lapo iki akuu bingung gingkjaksjd asdakh askdjahd askdha </p>
          </div>
          <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#Programming</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#Python</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#OpenCV</span>
          </div>
        </nuxt-link>
      </div>
    </div>
  </div>
</template>

<style>
@screen sm {
  .cards {
    @apply: my-5;
  }
}
</style>

// src/components/content.svelte
<script lang="ts">
    import Card from "./card.svelte";
</script>

<section class="section mt-6">
    <h2 class="title is-size-1 is-size-3-mobile has-text-centered">
        Kumpulan Konten Menarik
    </h2>

    <div class="columns mt-6 is-centered">
        <div class="column is-3 mx-3 my-3">
            <Card
                image="./images/imagethres.png"
                altImage="Image Thresholding with OpenCV Python3"
                href="https://medium.com/@gelembungsahabat/deteksi-warna-dengan-metode-image-thresholding-opencv-python-3-f3686de4308"
            >
                <h1 class="title is-size-4 is-size-4-mobile">
                    Image Thresholding with OpenCV Python3
                </h1>
                <p class="is-size-6">
                    Pengenalan dasar image thresholding beserta source codenya
                </p>
                <div class="tags mt-6">
                    <span class="tag is-primary is-light">#Programming</span>
                    <span class="tag is-info is-light">#Python</span>
                    <span class="tag is-danger is-light">#OpenCV</span>
                </div>
            </Card>
        </div>
        <div class="column is-3 mx-3 my-3">
            <Card
                image="./images/reactjs.png"
                altImage="Pengenalan ReactJS"
                href="https://medium.com/@gelembungsahabat/pengenalan-reactjs-40ffa31ae9c7"
            >
                <h1 class="title is-size-4 is-size-4-mobile">
                    Pengenalan ReactJS
                </h1>
                <p class="is-size-6">
                    Pengenalan salah satu framework JS paling populer yaitu
                    ReactJS
                </p>
                <div class="tags mt-6">
                    <span class="tag is-primary is-light">#Programming</span>
                    <span class="tag is-info ">#JavaScript</span>
                    <span class="tag is-link">#ReactJS</span>
                </div>
            </Card>
        </div>
        <div class="column is-3 mx-3 my-3">
            <Card
                image="./images/persiapanreact.png"
                altImage="Persiapan Membuat Web dengan ReactJS"
                href="https://medium.com/@gelembungsahabat/persiapan-membuat-website-dengan-reactjs-435ccac65c54"
            >
                <h1 class="title is-size-4 is-size-4-mobile">
                    Persiapan Membuat Web dengan ReactJS
                </h1>
                <p class="is-size-6">
                    Materi tentang setup project ReactJS beserta penjelasannya
                </p>
                <div class="tags mt-6">
                    <span class="tag is-primary is-light">#Programming</span>
                    <span class="tag is-info ">#JavaScript</span>
                    <span class="tag is-link">#ReactJS</span>
                </div>
            </Card>
        </div>
    </div>

    <div class="columns mt-6 is-centered">
        <div class="column is-3 mx-3 my-3">
            <Card
                image="./images/staticwebreact1.png"
                altImage="Belajar Membuat Static Site Menggunakan ReactJS #part1"
                href="https://medium.com/@gelembungsahabat/belajar-membuat-static-site-menggunakan-reactjs-part1-4bb9a3a02307"
            >
                <h1 class="title is-size-4 is-size-4-mobile">
                    Belajar Membuat Static Site Menggunakan ReactJS #part1
                </h1>
                <p class="is-size-6">
                    Belajar membuat skeleton atau kerangka dari project web dan
                    belajar mengenai `Components`
                </p>
                <div class="tags mt-6">
                    <span class="tag is-primary is-light">#Programming</span>
                    <span class="tag is-info ">#JavaScript</span>
                    <span class="tag is-link">#ReactJS</span>
                </div>
            </Card>
        </div>
        <div class="column is-3 mx-3 my-3">
            <Card
                image="./images/git.png"
                altImage="Dasar VCS (Version Control System)"
                href="https://medium.com/@gelembungsahabat/dasar-vcs-version-control-system-789b6793bcb9"
            >
                <h1 class="title is-size-4 is-size-4-mobile">
                    Dasar VCS (Version Control System)
                </h1>
                <p class="is-size-6">
                    ini pengetahuan dasar tentang cara pengoperasian VCS. VCS
                    Bukan singkatan dari Video Call S*x ya, tapi Version Control
                    System. Dalam hal ini mengarah ke Git
                </p>
                <div class="tags mt-6">
                    <span class="tag is-primary is-light">#Programming</span>
                    <span class="tag is-warning is-light ">#Git</span>
                    <span class="tag">#Basic</span>
                </div>
            </Card>
        </div>
        <div class="column is-3 mx-3 my-3">
            <Card
                image="./images/pyqt5.jpg"
                altImage="Raspibot with PyQt5"
                href="https://github.com/gelembungsahabat/raspibot-pyqt5"
            >
                <h1 class="title is-size-4 is-size-4-mobile">
                    Raspibot with PyQt5
                </h1>
                <p class="is-size-6">
                    Membuat Raspibot dengan menggunakan Desktop App PyQt5
                </p>
                <div class="tags mt-6">
                    <span class="tag is-primary is-light">#Programming</span>
                    <span class="tag is-info is-light">#Python</span>
                    <span class="tag is-danger is-light">#OpenCV</span>
                    <span class="tag is-primary">#PyQt5</span>
                </div>
            </Card>
        </div>
    </div>
</section>
